spring:
  jpa:
    hibernate:
      ddl-auto: create-drop #운영중일 때는 validate 를 많이 사용함
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
    defer-datasource-initialization: true